-- MOVED. This interim file has been superseded by the managed migration runner.
--
-- The canonical migration now lives at:
--   apps/api/migrations/0001_orders_refund_initiated_at.sql
-- and is applied automatically by apps/api/scripts/migrate.mjs (see DEPLOY.md).
--
-- This placeholder is intentionally empty of DDL. Please delete it:
--   git rm apps/api/prisma/migrations-manual/2026-05-25_orders_refund_initiated_at.sql
