/**
 * Canonical Orkora brand renderer.
 *
 * Every place the brand appears in the web app goes through this file.
 * Three variants:
 *
 *   - `lockup`  rounded-square mark + stacked "Orkora" wordmark and the
 *               "PROFESSIONAL EVENT PLATFORM" tagline. The default
 *               brand presentation on the marketing landing, auth
 *               pages, OG cards, etc.
 *   - `mark`    rounded-square mark only. Used where space is tight
 *               (dashboard sidebar, compact footer, browser tab).
 *   - `wordmark` "Orkora" text only. Used when the mark sits adjacent
 *               in another element.
 *
 * Architectural change from the PNG-crop era:
 *   - The mark is a vector SVG at /brand/orkora-mark.svg, scales to
 *     any size without alignment drift, regenerated by sharp into the
 *     PNG ladder for browsers that need raster.
 *   - The wordmark + tagline are LIVE HTML TEXT in Inter, inheriting
 *     the current text colour via `currentColor` so the brand sits
 *     cleanly on dark marketing AND white dashboard surfaces with no
 *     per-surface PNG variant. Pass `wordmarkColor` to override.
 *   - The tagline is on by default in the `lockup` variant. Pass
 *     `tagline={false}` to suppress it for compact contexts.
 *
 * Backwards compat: existing callsites (className="h-20 w-auto",
 * width={320}, priority) still work without changes. The component
 * parses the `h-N` Tailwind class to drive both the mark height and
 * the live-text font sizes so the wordmark + tagline always scale in
 * lockstep with the mark.
 */

import Image from 'next/image';

type BrandVariant = 'lockup' | 'mark' | 'wordmark';

interface BrandProps {
  variant?: BrandVariant;
  /** Display width hint in CSS pixels. Used for next/image layout
   *  reservation only; final display size comes from the className
   *  height (e.g. h-20). */
  width?: number;
  /** Override the alt / aria-label. Defaults to "Orkora - Professional
   *  Event Platform" for the lockup, "Orkora" for mark/wordmark. */
  alt?: string;
  className?: string;
  /** Next/Image priority hint: true for above-the-fold renders. */
  priority?: boolean;
  /** Override the wordmark colour. Defaults to currentColor so the
   *  brand inherits the surrounding text colour. */
  wordmarkColor?: string;
  /** Render the "PROFESSIONAL EVENT PLATFORM" tagline beneath the
   *  wordmark in the `lockup` variant. Defaults to true. Set false
   *  for compact contexts (header strips with limited vertical room). */
  tagline?: boolean;
}

const MARK_SRC = '/brand/orkora-mark.svg';
const MARK_INTRINSIC = 100;
const TAGLINE_TEXT = 'PROFESSIONAL EVENT PLATFORM';

/**
 * Pull the height in CSS pixels out of a tailwind className. Tailwind
 * `h-N` is `0.25rem * N` = `4 * N px` at the default root font size.
 */
function parseHeightPx(className: string | undefined): number | undefined {
  if (!className) return undefined;
  const m = /\bh-(\d+)\b/.exec(className);
  if (!m) return undefined;
  return parseInt(m[1] ?? '0', 10) * 4;
}

export function Brand({
  variant = 'lockup',
  width,
  alt,
  className,
  priority = false,
  wordmarkColor,
  tagline = true,
}: BrandProps) {
  if (variant === 'mark') {
    const w = width ?? 32;
    return (
      <Image
        src={MARK_SRC}
        alt={alt ?? 'Orkora'}
        width={w}
        height={w}
        className={className}
        priority={priority}
      />
    );
  }

  if (variant === 'wordmark') {
    return (
      <span
        className={`inline-block font-semibold tracking-tight ${className ?? ''}`}
        style={{
          color: wordmarkColor ?? 'currentColor',
          letterSpacing: '-0.02em',
        }}
        aria-label={alt ?? 'Orkora'}
      >
        Orkora
      </span>
    );
  }

  /*
   * Lockup. Layout is mark + stacked text column (wordmark above,
   * tagline below). All three pieces scale together off the parent
   * className `h-N`:
   *   - mark    : h-full of the container (so 100% of heightPx)
   *   - wordmark: 0.56em of heightPx (Inter cap height + breathing)
   *   - tagline : 0.13em of heightPx, expanded letter-spacing
   *
   * The text column is centred vertically against the mark.
   */
  const heightPx = parseHeightPx(className) ?? width ?? 32;
  const wordmarkPx = Math.max(12, Math.round(heightPx * 0.56));
  const taglinePx = Math.max(7, Math.round(heightPx * 0.13));
  const showTagline = tagline && heightPx >= 56;

  return (
    <span
      role="img"
      aria-label={alt ?? 'Orkora - Professional Event Platform'}
      className={`inline-flex items-center gap-3 ${className ?? ''}`}
    >
      <Image
        src={MARK_SRC}
        alt=""
        width={MARK_INTRINSIC}
        height={MARK_INTRINSIC}
        className="h-full w-auto"
        priority={priority}
        aria-hidden
      />
      <span
        className="inline-flex flex-col items-start justify-center"
        style={{ color: wordmarkColor ?? 'currentColor' }}
      >
        <span
          className="font-semibold leading-none"
          style={{
            fontSize: `${wordmarkPx}px`,
            letterSpacing: '-0.02em',
          }}
        >
          Orkora
        </span>
        {showTagline && (
          <span
            className="font-medium opacity-70"
            style={{
              fontSize: `${taglinePx}px`,
              letterSpacing: '0.22em',
              marginTop: `${Math.round(heightPx * 0.06)}px`,
              whiteSpace: 'nowrap',
            }}
          >
            {TAGLINE_TEXT}
          </span>
        )}
      </span>
    </span>
  );
}

export default Brand;
